name: Docker Image CI


on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build

    - name: Log into registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Publish
      uses: falti/dotenv-action@v0.2
      run: |
        docker tag piotrmaks/grcov:${{ steps.dotenv.outputs.grcov_version }} piotrmaks/grcov:latest
